name: on-push-home-page-staging
on:
  push:
    branches:
      - home-page-staging
jobs:
  UI_test:
    name: Test home-page-staging branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm run test
  style_test:
    name: Check html,css,javascript coding style with prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npx prettier --check .
