name: on-push-testing-staging
on:
  push:
    branches:
      - testing-staging
jobs:
  style_test:
    name: Coding Style Test (on push to [testing-staging] branch)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npx prettier --check .
