name: on-push-home-explore-staging
on:
  push:
    branches:
      - home-explore-staging
jobs:
  UI_test:
    name: UI Test (home-explore-staging branch)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run home-explore-staging-test
  style_test:
    name: Coding Style Test (home-explore-staging branch)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npx prettier --check .
   lint_JS_test:
    name: Linting JS Test (home-explore-staging branch)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npx eslint .
