name: on-push-testing
on:
  push:
    branches:
      - testing
jobs:
  style_test:
    name: Coding Style Test (testing branch)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: pwd
      - run: ls
      - run: npx prettier --check .
