name: on-push-create-skeletons-staging
on:
  push:
    branches:
      - create-skeletons-staging
jobs:
  UI_test:
    name: UI Test (create-skeletons-staging branch)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run create-skeletons-staging-test
  style_test:
    name: Coding Style Test (create-skeletons-staging branch)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npx prettier --check .
  lint_JS_test:
    name: Linting JS Test (create-skeletons-staging branch)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npx eslint .
